# Anaconda

- Python을 설치하는 방법
- Jupyter도 설치됨

# Jupyter 

- Python을 사용하는 방법


In [2]:
import numpy

In [3]:
x = [100,100,200,300,500, 500,700,700,800,900,900,1000]

In [4]:
numpy.mean(x) #평균

558.3333333333334

In [5]:
numpy.median(x) #중간값

600.0

In [6]:
from scipy.stats import mode

In [7]:
mode(x) #최빈값

ModeResult(mode=array([100]), count=array([2]))

In [8]:
# 최빈값이 여러개일 경우 작은 값을 반환함

In [9]:
help(mode)

Help on function mode in module scipy.stats.stats:

mode(a, axis=0, nan_policy='propagate')
    Return an array of the modal (most common) value in the passed array.
    
    If there is more than one such value, only the smallest is returned.
    The bin-count for the modal bins is also returned.
    
    Parameters
    ----------
    a : array_like
        n-dimensional array of which to find mode(s).
    axis : int or None, optional
        Axis along which to operate. Default is 0. If None, compute over
        the whole array `a`.
    nan_policy : {'propagate', 'raise', 'omit'}, optional
        Defines how to handle when input contains nan. 'propagate' returns nan,
        'raise' throws an error, 'omit' performs the calculations ignoring nan
        values. Default is 'propagate'.
    
    Returns
    -------
    mode : ndarray
        Array of modal values.
    count : ndarray
        Array of counts for each mode.
    
    Examples
    --------
    >>> a = np.array([[6, 8, 3, 

In [10]:
numpy.max(x)

1000

In [11]:
numpy.min(x)

100

In [12]:
numpy.var(x) # 분산

95763.88888888889

In [13]:
numpy.std(x) # 표준편차

309.45741046045237

In [14]:
numpy.quantile(x, .25) # 1사분위수

275.0

In [15]:
numpy.quantile(x, .5) # 2사분위수

600.0

In [16]:
numpy.median(x) # 중간값 = 2사분위수

600.0

In [17]:
numpy.quantile(x, .75) # 3사분위수

825.0

In [18]:
a = [0, 500, 500, 500, 1000]

In [19]:
numpy.quantile(a, .25)

500.0

In [20]:
numpy.quantile(a, .5)

500.0

In [21]:
numpy.quantile(a, .75)

500.0

In [22]:
x = [0,0,0,0,0,0,0,0,0,100]

## 이항분포

In [23]:
from numpy.random import binomial

In [24]:
help(binomial)

Help on built-in function binomial:

binomial(...) method of mtrand.RandomState instance
    binomial(n, p, size=None)
    
    Draw samples from a binomial distribution.
    
    Samples are drawn from a binomial distribution with specified
    parameters, n trials and p probability of success where
    n an integer >= 0 and p is in the interval [0,1]. (n may be
    input as a float, but it is truncated to an integer in use)
    
    Parameters
    ----------
    n : int or array_like of ints
        Parameter of the distribution, >= 0. Floats are also accepted,
        but they will be truncated to integers.
    p : float or array_like of floats
        Parameter of the distribution, >= 0 and <=1.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``n`` and ``p`` are both scalars.
        Otherwise, ``np.broadcas

In [25]:
binomial(100,.3)
# n=100, p=.3

31

In [26]:
binomial(100,.3)
# n=100, p=.3
# 확률이 같다고 해도 항상 같은 값이 나오지 않음

37

In [27]:
binomial(100, .3, 30)
# n=100, p=.3, 시뮬레이션 수=30

array([31, 37, 27, 38, 25, 26, 32, 35, 23, 25, 35, 34, 31, 32, 28, 28, 41,
       31, 35, 31, 37, 25, 35, 31, 35, 29, 28, 25, 26, 27])

In [28]:
x = binomial(100, .3, 30)

In [29]:
min(x)

22

In [30]:
max(x)

37

In [31]:
수익 = 0
준비 = 20
for 고객수 in x:
    if 고객수<=준비:
        수익 = 수익 + (준비-고객수) * -10000
        수익 = 수익 + 고객수 * 1000
    else:
        수익 = 수익 + 30 * 1000
수익

900000

In [32]:
보험료 = 300
지급액 = 1_000
고객 = 지급액 / 10
장사 = 100
사망자 = binomial(고객, .1, 장사)
매출 = 보험료 * 고객
지급 = 지급액 * 사망자
numpy.mean(매출 - 지급)

20300.0

## 기하분포

In [40]:
이탈성공 = 0
기간 = 0
while 이탈성공 == 0:
    이탈성공 = binomial(1, .05)
    기간 = 기간 + 1
기간

10

In [41]:
from numpy.random import geometric

In [42]:
기간 = geometric(.05, 100)
# 이탈률 5%일때 100명의 고객이 며칠 후 이탈할지

In [43]:
기간 * 0.5 - 10
# 기간 * 고객이 사용하는 비용 - 고객 획득 비용

array([ 5. , 10.5, -2. , -6.5, -7. , -5. , -9. , 11. , -4.5, -5.5, -5.5,
       -3.5, -2.5, -3.5, 58.5, 13.5, -3. , -5. , -4.5, -3. , -9.5, 11. ,
       16.5, -7. , -9.5,  5.5, 16.5, 23.5,  9. , -4. ,  0.5, -4.5, -2. ,
        7. , -2. , 16.5, 10.5, -2.5, -9. , -9.5,  9.5,  0. , -1. , -0.5,
       -2.5, 11. , -9. ,  4. , -9.5, -7. , -5.5,  9. , -8.5, -1.5,  1.5,
       -4. , -4. , -4. , -9.5,  3.5, 10.5,  6. , -9. , -2. ,  7. , 21. ,
       23. , -5. , 16.5, -7.5,  8. , -3. , -7.5,  7. , -1. , -5. , -9. ,
       29.5, -1. , -7. ,  1. , -2. , -6. , -4.5, -8. , -9.5, -6.5, -7. ,
       -6. ,  4. , -9. , -8.5, -1.5, -9.5, 14.5, -0.5, -3.5, -5. , -8. ,
        1.5])

In [44]:
numpy.sum(기간 * 0.5 - 10)

55.0

## 음이항분포

In [53]:
짜증 = 0
기간 = 0
while 짜증 < 3:             # 3번째는 못 참는다
    사건 = binomial(1, .05) # 5%의 확률로 사건 발생
    if 사건 == 1:           # 사건이 일어나면
        짜증 = 짜증 + 1      # 짜증이 증가
    기간 = 기간 + 1
기간

34

In [64]:
# 세 번 짜증나게 하면 폭발

In [65]:
폭발 = []
for i in range(100):
    짜증 = 0
    기간 = 0
    while 짜증 < 3:
        사건 = binomial(1, .05)
        if 사건 == 1:
            짜증 = 짜증 + 1
        기간 = 기간 + 1
    폭발.append(기간)

In [55]:
폭발

[81,
 31,
 12,
 38,
 25,
 98,
 37,
 47,
 15,
 22,
 41,
 126,
 112,
 101,
 36,
 69,
 37,
 38,
 86,
 39,
 44,
 85,
 68,
 56,
 51,
 24,
 13,
 118,
 36,
 97,
 33,
 102,
 79,
 23,
 69,
 189,
 63,
 146,
 23,
 55,
 39,
 63,
 79,
 39,
 44,
 29,
 30,
 64,
 55,
 124,
 71,
 50,
 32,
 61,
 33,
 83,
 57,
 19,
 112,
 30,
 22,
 34,
 65,
 30,
 95,
 51,
 47,
 28,
 58,
 20,
 53,
 40,
 68,
 68,
 87,
 32,
 15,
 33,
 53,
 80,
 57,
 13,
 20,
 30,
 45,
 105,
 117,
 21,
 99,
 53,
 46,
 62,
 58,
 54,
 57,
 17,
 18,
 108,
 22,
 74]

In [51]:
from numpy.random import negative_binomial

In [52]:
negative_binomial

<function RandomState.negative_binomial>

In [66]:
# 이틀 연속으로 짜증나게 하면 폭발

In [61]:
폭발 = []
for i in range(100):
    짜증 = 0
    기간 = 0
    while 짜증 <2:             # 2번 연속은 못 참는다
        사건 = binomial(1, .1) # 화날 확률 10%
        if 사건 == 1:          # 사건이 일어난다면
            짜증 = 짜증 + 1     # 짜증 1 증가
        else:
            짜증 = 0
        기간 = 기간 + 1
    폭발.append(기간)

In [63]:
폭발

[536,
 747,
 100,
 85,
 13,
 392,
 534,
 1739,
 830,
 182,
 497,
 206,
 331,
 907,
 133,
 878,
 173,
 275,
 481,
 198,
 17,
 230,
 45,
 395,
 457,
 194,
 173,
 37,
 79,
 48,
 220,
 88,
 470,
 296,
 298,
 30,
 1066,
 459,
 303,
 867,
 70,
 139,
 233,
 372,
 210,
 352,
 81,
 165,
 215,
 481,
 571,
 643,
 60,
 87,
 268,
 73,
 136,
 324,
 194,
 749,
 607,
 388,
 143,
 776,
 266,
 908,
 688,
 297,
 357,
 327,
 14,
 63,
 71,
 153,
 503,
 230,
 179,
 1789,
 458,
 581,
 241,
 277,
 315,
 602,
 394,
 293,
 309,
 339,
 1296,
 1226,
 1178,
 299,
 111,
 75,
 317,
 1362,
 773,
 201,
 731,
 593]

## 포아송 분포

In [67]:
from numpy.random import poisson

In [93]:
binomial(100, .3, 50) # 100

array([10,  8, 12,  8,  8,  9,  6,  8,  8,  7, 16,  8, 11, 11, 11, 14, 11,
        7,  9, 11,  9,  9,  5,  9,  8,  7,  8,  8,  7,  8, 10,  9,  9,  9,
        6,  8, 11,  8,  7,  8,  9, 11, 14,  6, 10,  7, 11,  6,  9,  7])

In [95]:
poisson(30, 50) # 하루 평균 30명 방문할 때 50일간 방문인원 수
# 총 인원 (최대 인원)이 정해져 있지 않음

array([36, 29, 30, 32, 26, 29, 31, 33, 28, 35, 30, 32, 16, 26, 27, 28, 40,
       27, 37, 33, 33, 31, 24, 25, 30, 20, 40, 25, 24, 31])